Aom.Mvc/Controllers/AomObjectsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CustomLogic;

namespace Aom.Mvc.Controllers
{
    public class AomObjectsController : Controller
    {
        private AomDbContext db = new AomDbContext();

        // GET: AomObjects
        public ActionResult Index(Guid? id, int amount = 10, int page = 1, string query = "")
        {
            // Menu Stuff list of AomMeta to make the menu from
            ViewBag.AomMetas = db.AomMetas.Take(10).ToList();
            ViewBag.ObjectType = id?.ToString();
            ViewBag.Query = query?.ToString();
            IQueryable<AomObject> tableData = db.AomObjects;

            // Table stuff filtering sorting etc
            if (id != null)
            {
                tableData = tableData.Where(c => c.AomMetaId == id); // filter by type if there is an id
                
            }
            
            if (!string.IsNullOrEmpty(query)) // filter buy query
            {
                var AomFieldObjects = db.AomFieldObjects.Where(c => c.Value.Contains(query));
                tableData = tableData.Where(c => AomFieldObjects.Select(d => d.AomObjectId).Contains(c.Id));
                tableData = tableData.Where(c => c.Name.Contains(query)); // search name

                // this will crash
                //tableData = tableData.Where(c => c.Name.Contains(query) ||
                // c.AomFieldObjects.Any(cc => cc.Value.Contains(query))); // serach values
            }

            ViewBag.TotalRecords = tableData.Count();
           // var viewModel = tableData.OrderBy(c => c.Id).Skip((page - 1) * amount).Take(amount).ToList();

            return View(tableData.OrderBy(c => c.Id).Skip((page - 1) * amount).Take(amount).ToList());
        }

        // GET: AomObjects/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AomObject aomObject = db.AomObjects.Find(id);
            if (aomObject == null)
            {
                return HttpNotFound();
            }
            return View(aomObject);
        }

        // GET: AomObjects/Create/AomMetaId
        public ActionResult Create(Guid id)
        {
            AomObject viewModel = new AomObject();
            viewModel.AomMeta = db.AomMetas.FirstOrDefault(c => c.Id == id); // used to display the type
            viewModel.AomMetaId = viewModel.AomMeta.Id;
            viewModel.AomFieldObjects = viewModel.AomMeta.AomFieldMetas.Select(c => new AomFieldObject { AomFieldMetaId = c.Id, AomFieldMeta = c}).ToList();

            // now make all the drop donw lists
            foreach (var aomFieldMeta in viewModel.AomMeta.AomFieldMetas)
            {
                if (aomFieldMeta.Name.Contains("Id"))
                {
                    // Get a list of object that match the 
                    var testMe = db.RelationshipMetas.FirstOrDefault(cc => cc.FkAomFieldMetaId == aomFieldMeta.Id);
                    if (testMe != null)
                    {
                        var dropDownObjects = db.AomObjects.Where(c => c.AomMetaId == testMe.PkAomMetaId).ToList();
                        ViewData[aomFieldMeta.Name] = dropDownObjects;
                    }
                }
            }
            
            return View(viewModel);
        }

        // POST: AomObjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AomObject aomObject)
        {
            aomObject.Id = Guid.NewGuid();
            if (ModelState.IsValid)
            {
                db.AomObjects.Add(aomObject);

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aomObject);
        }

        // GET: AomObjects/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AomObject aomObject = db.AomObjects.Find(id);
            if (aomObject == null)
            {
                return HttpNotFound();
            }

            // fill up the ViewData with the Id and Display Name for the linkable objects if any 
            var otherKeys = db.RelationshipMetas.Where(c => c.FkAomMetaId == aomObject.AomMetaId);
            return View(aomObject);
        }

        // POST: AomObjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( AomObject aomObject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aomObject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aomObject);
        }

        // GET: AomObjects/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AomObject aomObject = db.AomObjects.Find(id);
            if (aomObject == null)
            {
                return HttpNotFound();
            }
            return View(aomObject);
        }

        // POST: AomObjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            AomObject aomObject = db.AomObjects.Find(id);
            db.AomObjects.Remove(aomObject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Aom.Mvc/Views/AomObjects/Create.cshtml
@using System.Collections
@model CustomLogic.AomObject

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create @Html.DisplayFor(model => model.AomMeta.Name)</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Creat new @Html.DisplayFor(model=>model.AomMeta.Name)</h4>
        <hr />
        

        @Html.HiddenFor(model => model.AomMetaId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

                    @for (var counter = 0; counter < Model.AomFieldObjects.Count(); counter++)
                    {
                        <div class="form-group">
                            <div class="control-label col-md-2">@Html.DisplayFor(x => Model.AomFieldObjects[counter].AomFieldMeta.Name)</div>
                            <div class="col-md-10">
                                
                                @Html.HiddenFor(modelItem => Model.AomFieldObjects[counter].AomFieldMetaId)
                                @Html.HiddenFor(modelItem => Model.AomFieldObjects[counter].AomObjectId)

                                @if (!Model.AomFieldObjects[counter].AomFieldMeta.Name.Contains("Id") && Model.AomFieldObjects[counter].AomFieldMeta.Name != "Id")
                                {
                                    @Html.EditorFor(modelItem => Model.AomFieldObjects[counter].Value)
                                }
                                else
                                {
                                    if (ViewData[Model.AomFieldObjects[counter].AomFieldMeta.Name] != null)
                                    {
                                        @Html.DropDownList(Model.AomFieldObjects[counter].AomFieldMeta.Name, new SelectList((IEnumerable)ViewData[Model.AomFieldObjects[counter].AomFieldMeta.Name], "Id", "Name"), new { htmlAttributes = new { @class = "form-control" } })
                                    }
                                    else
                                    {
                                        <div class="control-label col-md-2">No objects exist or relationsship not set up</div>
                                    }
                                }
                            </div>
                        </div>
                    }

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
        </div>
        }

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aom.Mvc/Views/AomObjects/Delete.cshtml
@model CustomLogic.AomObject

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AomObject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AomMetaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AomMetaId)
        </dd>

    

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Aom.Mvc/Views/AomObjects/Details.cshtml
@model CustomLogic.AomObject

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AomObject</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AomMetaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AomMetaId)
        </dd>

      

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Aom.Mvc/Views/AomObjects/Edit.cshtml
@using System.Collections
@model CustomLogic.AomObject

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var fields = Model.AomFieldObjects.ToList();
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit @Html.DisplayFor(model=>model.AomMeta.Name)</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        @Html.HiddenFor(model => model.AomMetaId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        
        @for (var counter = 0; counter < fields.Count(); counter++)
        {
            <div class="form-group">
                <div class="control-label col-md-2">@Html.DisplayFor(x => fields[counter].AomFieldMeta.Name)</div>
                <div class="col-md-10">

                    @Html.HiddenFor(modelItem => fields[counter].AomFieldMetaId)
                    @Html.HiddenFor(modelItem => fields[counter].AomObjectId)

                    @if (!fields[counter].AomFieldMeta.Name.Contains("Id"))
                    {
                        @Html.TextBoxFor(modelItem => fields[counter].Value, null, new { @class = "form-control" })
                    }
                    else
                    {



                        if (ViewData[fields[counter].AomFieldMeta.Name] != null)
                        {
                            @Html.DropDownList(fields[counter].AomFieldMeta.Name, new SelectList((IEnumerable)ViewData[fields[counter].AomFieldMeta.Name], "Id", "Name"), new { htmlAttributes = new { @class = "form-control" } })
                        }
                        else
                        {
                            <div class="control-label col-md-2">No objects exist or relationsship not set up view data not found for @Html.Raw(fields[counter].AomFieldMeta.Name)</div>
                        }
                    }
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aom.Mvc/Views/AomObjects/Index.cshtml
@using CustomLogic
@model IEnumerable<CustomLogic.AomObject>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h2>Create</h2>
    <ul class="nav navbar-nav">
        @foreach (AomMeta item in ViewBag.AomMetas)
        {
            <li>@Html.ActionLink(item.Name, "Create", "AomObjects", new { id = item.Id }, null)</li>
        }
    </ul>
</div>



<div class="row">
    <h2>Limiting Table</h2>
    <ul class="nav navbar-nav">
        @foreach (AomMeta item in ViewBag.AomMetas)
        {
            <li>@Html.ActionLink(item.Name, "Index", "AomObjects", new { id = item.Id }, null)</li>
        }
    </ul>
 
    <form action="@Html.Raw("/AomObjects/index/" + ViewBag.ObjectType)" method="get">
        <input id="query" name="query" maxlength="100" type="text" value="@Html.Raw(ViewBag.query)"/>
        <input type="submit" id="submit" value="Search" />
    </form>
</div>


<div>Total records = @Html.ViewBag.TotalRecords</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AomMetaId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AomMeta.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>


        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AomMetaId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AomMeta.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @foreach (var innerItem in item.AomFieldObjects)
                {
                    <div>
                        @Html.DisplayFor(modelInnerItem => innerItem.Value)
                    </div>
                }

            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>