Aom.Mvc/Controllers/AOMMetaServiceCreatorController.cs
using System.Web.Mvc;
using CustomLogic;
using CustomLogic.Services.AOMMetaCreatorService;
using CustomLogic.Services.AOMMetaCreatorService.Connectors;

namespace Aom.Mvc.Controllers
{
    public class AOMMetaServiceCreatorController : Controller
    {
        // GET: AOMMetaServiceCreator
        public ActionResult Index()
        {
            return View(new ResetTablesModel
            {
                userName = "",
                password = "",
                tables = "Opportunity,Task,Account,Contact,OpportunityContactRole"
            });
        }

        [HttpPost]
        public ActionResult Index(ResetTablesModel mode )
        {
            var db = new AomDbContext();
            db.Database.ExecuteSqlCommand(@"  delete[dbo].[RelationshipObject]
        delete[dbo].[RelationshipMeta]
        delete[dbo].[AomFieldObject]
        delete[dbo].[AomObject]
        delete[dbo].[AomFieldMeta]
        delete[dbo].[FieldTypes]
        delete[dbo].[AomMeta]");

            AOMMetaCreatorService service = new AOMMetaCreatorService(new SalesforceConnector());
            var result = service.CreateTables(mode.userName, mode.password, mode.tables.Split(','));
            return View();
        }
    }

    public class ResetTablesModel
    {
        public string userName { get; set; }
        public string password { get; set; }
        public string tables { get; set; }
    }
}

Aom.Mvc/Views/AOMMetaServiceCreator/Index.cshtml
@model Aom.Mvc.Controllers.ResetTablesModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Reset your modles</h2>

@using (@Html.BeginForm("Index", "AOMMetaServiceCreator", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(model => model.userName, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.userName, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control", @type = "password"} })
        @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.tables, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.tables, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.tables, "", new { @class = "text-danger" })
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Create" class="btn btn-default" />
    </div>
</div>
    }